### ISSUE TITLE
composer install runs indefinitely

### ISSUE THREAD

**Issue by fritzmg** [magephp/magallanes#15]
PHP: 7.1.4
OS: Windows 10 x64
Composer version: 1.7.2
Magallanes: 4.0.0

My `.mage.yml` is configured to run `composer/install` on `pre-deploy`. Usually this operation just takes a second - assuming all dependencies in the `composer.lock` file are already installed. However, for some reason when Magallanes executes it, it runs forever - no matter what timeout I set (well the most I tried is 5 minutes, but it should never take that long or even longer).
```
$ mage deploy staging
Starting Magallanes

    Environment: staging
    Release ID: 20180910133336
    Logfile: ./.mage/20180910_133336.log
    Strategy: Releases
    Branch: master

    Starting Pre Deploy tasks:
        Running [Git] Change Branch (master) ... SKIPPED
        Running [Git] Update ... OK
        Running [Composer] Install ... Oops, exception thrown while running command deploy

In MageApplication.php line 54:

  Caught exception


In Process.php line 1154:

  The process "composer install --optimize-autoloader" exceeded the timeout of 120 seconds.

```
This is my current (redacted) `.mage.yml`:
```yml
magephp:
    log_dir: './.mage'
    environments:
        staging:
            user: …
            branch: master
            host_path: …
            releases: 4
            exclude: …
            hosts: …
            pre-deploy:
                - git/update
                - composer/install: { timeout: 300 }
            on-deploy:
            on-release:
            post-release:
            post-deploy:
```
Is there any way to make the console output or logging more verbose, to figure out what Magallanes is actually doing?
