### ISSUE TITLE
Shared files/folders

### ISSUE THREAD

**Issue by DavidGarciaCat** [magephp/magallanes#3]
Hello,

I have been reviewing the configuration docs here https://magephp.github.io/docs/configuration/ but I cannot see any rule to share some files and folders between all releases.

An example:

Imagine I want to deploy my PHP code on 3 different servers (`dev`, `uat` and `prod`) and each one has a different database configuration details. After the first deployment for each server, I have the required configuration file, so I don't need to overwrite that file, due my local environment can use another credentials.

How can I keep the shared `configuration.php` file (maybe another symlink) for all releases on each server?

Thanks,

**Comment by hectornguyen** [comment]
Hi @DavidGarciaCat,
Please take my apology for this late response, and poor documentation but let me answer your question.

Magallanes is able to do what exactly you want, that is a core feature. To do so, you need to add new section into `extras`

```yml
extras:
  enabled: true
  directory: shared
  shared:
    enabled: true
    linking_strategy: absolute
    linked_files:
      - app/config/database.php
      - app/config/configuration.php
    linked_folders:
      - media
      - var/session
      - var/cache
```
`directory` (in this case is shared) must be existed on your servers and so do the `linked_files` and `linked_folders`.

Regarding to the previous example, your `shared` directory should look exactly like this:
```
shared
├── app
│   ├── config
│   │   ├── database.php
│   │   └── config.php
│   └── general.yml
├── var
│   ├── session
│   └── cache
└── media
```

Then whenever you deploy your project with Magallens, all files and folders you declared in `shared` section will be linked (absolute path) in your release folder.

Hope it helps and Sorry for any inconvenience you had,
Hector.
