### ISSUE TITLE
Per Host Configuration is not working

### ISSUE THREAD

**Issue by DavidGarciaCat** [magephp/magallanes#7]
Based on this documentation http://magephp.com/#cookbook-per-host-config I have tried to add these settings:

```
hosts:
  - 12.34.56.78:
    tasks:
      on-deploy:
        - filesystem/link-shared-files
        # other tasks here
        - symfony2/cache-warmup: {env: prod}
  - 12.34.56.79:
    tasks:
      on-deploy:
        - filesystem/link-shared-files
        # other tasks here
        - symfony2/cache-warmup: {env: api}
```

But the deployment command returns this output:

```
	Deploying to 0
		Running Deploy via TarGz (with Releases) [built-in] ... FAIL
		Running Linking files/folders from the shared folder into the current release [built-in] ... OK
	Make sure all paths given exist on the host : .
```

Any idea what is happening and how to fix this?

Thanks,
